# This file is machine-generated - editing it directly is not advised

[[ArgTools]]
git-tree-sha1 = "ed68c30deded537749c99f012873bb16708c6fb6"
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Tar]]
deps = ["ArgTools", "SHA"]
git-tree-sha1 = "62f8db5121d769931544a561bef2022e1706fdcf"
repo-rev = "master"
repo-url = "https://github.com/JuliaIO/Tar.jl.git"
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.5.0"
